export const cartActionType = {
    ADD_ITEM_TO_CART: 'ADD_ITEM_TO_CART',
    REMOVE_ITEM_FROM_CART: 'REMOVE_ITEM_FROM_CART',
    CLEAR_CART: 'CLEAR_CART',
    TOGGLE_CART: 'TOGGLE_CART',
    SAVE_ADDRESS: 'SAVE_ADDRESS',
    SAVE_PAYMENT_METHOD: 'SAVE_PAYMENT_METHOD',
};
