export const orderActionType = {
    CREATE_ORDER: 'CREATE_ORDER',
    CREATE_ORDER_SUCCESS: 'CREATE_ORDER_SUCCESS',
    CREATE_ORDER_FAILED: 'CREATE_ORDER_FAILED',

    GET_ORDER: 'GET_ORDER',
    GET_ORDER_SUCCESS: 'GET_ORDER_SUCCESS',
    GET_ORDER_FAILED: 'GET_ORDER_FAILED',

    RESET_MESSAGE: 'RESET_MESSAGE',

    GET_ORDER_LIST: 'GET_ORDER_LIST',
    GET_ORDER_LIST_SUCCESS: 'GET_ORDER_LIST_SUCCESS',
    GET_ORDER_LIST_FAILED: 'GET_ORDER_LIST_FAILED',
    CLEAR_ORDER_DETAILS: 'CLEAR_ORDER_DETAILS',
};
