export const productActionType = {
    FETCH_PRODUCTS: 'FETCH_PRODUCTS',
    FETCH_PRODUCTS_SUCCESS: 'FETCH_PRODUCTS_SUCCESS',
    FETCH_PRODUCTS_FAILED: 'FETCH_PRODUCTS_FAILED',
    FETCH_PRODUCT_DETAILS: 'FETCH_PRODUCT_DETAILS',
    FETCH_PRODUCT_DETAILS_SUCCESS: 'FETCH_PRODUCT_DETAILS_SUCCESS',
    FETCH_PRODUCT_DETAILS_FAILED: 'FETCH_PRODUCT_DETAILS_FAILED',
};
