export const productActionType = {
    FETCH_PRODUCTS: 'FETCH_PRODUCTS',
    FETCH_PRODUCTS_SUCCESS: 'FETCH_PRODUCTS_SUCCESS',
    FETCH_PRODUCTS_FAILED: 'FETCH_PRODUCTS_FAILED',

    FETCH_PRODUCT_DETAILS: 'FETCH_PRODUCT_DETAILS',
    FETCH_PRODUCT_DETAILS_SUCCESS: 'FETCH_PRODUCT_DETAILS_SUCCESS',
    FETCH_PRODUCT_DETAILS_FAILED: 'FETCH_PRODUCT_DETAILS_FAILED',

    DELETE_PRODUCT: 'DELETE_PRODUCT',
    DELETE_PRODUCT_SUCCESS: 'DELETE_PRODUCT_SUCCESS',
    DELETE_PRODUCT_FAILED: 'DELETE_PRODUCT_FAILED',

    CREATE_PRODUCT: 'CREATE_PRODUCT',
    CREATE_PRODUCT_SUCCESS: 'CREATE_PRODUCT_SUCCESS',
    CREATE_PRODUCT_FAILED: 'CREATE_PRODUCT_FAILED',
    CREATE_PRODUCT_RESET: 'CREATE_PRODUCT_RESET',

    UPDATE_PRODUCT: 'UPDATE_PRODUCT',
    UPDATE_PRODUCT_SUCCESS: 'UPDATE_PRODUCT_SUCCESS',
    UPDATE_PRODUCT_FAILED: 'UPDATE_PRODUCT_FAILED',
    UPDATE_PRODUCT_RESET: 'UPDATE_PRODUCT_RESET',
};
