export const userActionType = {
    LOGIN: 'LOGIN',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILED: 'LOGIN_FAILED',
    LOGOUT: 'LOGOUT',

    SIGNUP: 'SIGNUP',
    SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
    SIGNUP_FAILED: 'SIGNUP_FAILED',

    GET_PROFILE: 'GET_PROFILE',
    GET_PROFILE_SUCCESS: 'GET_PROFILE_SUCCESS',
    GET_PROFILE_FAILED: 'GET_PROFILE_FAILED',

    UPDATE_PROFILE: 'UPDATE_PROFILE',
    UPDATE_PROFILE_SUCCESS: 'UPDATE_PROFILE_SUCCESS',
    UPDATE_PROFILE_FAILED: 'UPDATE_PROFILE_FAILED',
    UPDATE_PROFILE_RESET: 'UPDAT_PROFILE_RESET',

    GET_LIST_USER: 'GET_LIST_USER',
    GET_LIST_USER_SUCCESS: 'GET_LIST_USER_SUCCESS',
    GET_LIST_USER_FAILED: 'GET_LIST_USER_FAILED',

    SET_ERROR: 'SET_ERROR',
    SET_SUCCESS: 'SET_SUCCESS',
};
